### PR TITLE
Upgrade to 4.2.0 and some improvements

### PR DESCRIPTION
**Pull request by brenard**
Hi,

I upgrade your _DEBIAN_ branch to new version _4.2.0_ and made some fixes and improvements.

Regards,

Benjamin

### CODE REVIEW

**Comment by raoulbhatia** [comment]
Thanks!  I'll have a look shortly.

**Comment by raoulbhatia** [comment]
Hi @brenard . Sorry that it took a little longer to review the pull request.

On first look, it seems that we're mixing patches that should go into upstream with patches that belong to DEBIAN customization.  Means:  Patches outside of ./debian/ should go to upstream.

See, for example, 0260c46df48c63a4fa405c32608f2281298008e6.

However, I do see a lot of good stuff on your PR.  Can we find a way to work together to untangle this?  i.e. by cherry-picking or similar?

Thanks for your contribution!
Raoul

**Comment by raoulbhatia** [comment]
Hi @brenard - I've looked at your PR and have cherry-picked the important patches into my DEBIAN-4.2.0 branch.  Would you kindly review it to see if I missed something?

Thanks,
Raoul
PS. I've also created a DEBIAN-4.2.1 branch to prep for 4.2.1.

**Comment by brenard** [comment]
Hi @raoulbhatia, thank you for that and I'm sorry for my silence. I will review your DEBIAN-4.2 branch and identify which commits need to be proposed upstream.
Thanks,
Benjamin
PS : Nice for your 4.2.1 packaging !

**Comment by brenard** [comment]
I mean this commit is important : https://github.com/raoulbhatia/backuppc/pull/1/commits/0260c46df48c63a4fa405c32608f2281298008e6

I permit to fix build process on machine without _backuppc_ user (like building machine).

Futhermore, I mean you could picked this other commit : https://github.com/raoulbhatia/backuppc/pull/1/commits/94a7b92e6a2673570d0f81c908642ee65ea5b4bb

I just adapt _config.pl_ default file to be adapted to Debian environment on more verbose about _--protect-args_ rsync parameter which break _rrsync_ usage and which not present on the original Debian packaging.

Thanks,

**Comment by brenard** [comment]
My https://github.com/raoulbhatia/backuppc/commit/0260c46df48c63a4fa405c32608f2281298008e6 commit is just a workaround for Debian building package process on host without _backuppc_ user. By setting _while(0)_, I disable the following _while_ block that try to determine _backuppc_ user infos, which fail on host without _backuppc_ user. I first try to use _--no-set-perms_ parameter of _configure.pl_ script in _debian/rules_ file but it's not working.

This workaround could certainly be fixed be using a more graceful solution but it's currently the easier way for me.

I will try to see if the _--no-set-perms_ parameter could be a proper solution by fixing it effect in _configure.pl_ file. In this case, I could propose a PR upstream for that and we could use it to fix this problem by just using _--no-set-perms_ parameter in _debian/rules_ file, like I first tried.

**Comment by raoulbhatia** [comment]
Thanks!  I do understand the problem and that's why I've added the manual creation of the `backuppc` user as a step in https://github.com/backuppc/backuppc/wiki/Build-Your-Own-Packages#build-preparations

Another way that comes to my mind is to add this as a patch in `./debian/patches/` as a temporary fix specific to Debian.
(And this needs to be cleaned up anyways...)

Raoul

**Comment by raoulbhatia** [comment]
See #4 #5 and #6

Thanks again for your support.  Let's see to get this added! 👍

**Comment by brenard** [comment]
Your right, use _./debian/patches/_ is the right way to do that. I need update my _DEBIAN_ branch to be compliant with your one. After that, I will try to propose you a PR with this method. Thank you !

**Comment by raoulbhatia** [comment]
Cool! 👍

**Pull request closed without merging**
